name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: docker-compose build
      - name: Run tests
        run: docker-compose tun test
